version: "3.3"

services:

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ./api
    network_mode: host
    env_file:
      - .env
    restart: on-failure
    ports:
      - "7777:7777"
    depends_on:
      - rabbitmq
      - mongo


  worker:
    build:
      context: ./ai_worker
    restart: on-failure
    network_mode: host
    env_file:
      - .env
    depends_on:
      - rabbitmq

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongo_db:/var/lib/mongodb/data

volumes:
  mongo_db: