# TODO move to MONGO


LYRICS_ANALYSIS_PROMPT = ("YOU WILL RECEIVE A TEXT WITH SONG LYRICS."
                          " YOU NEED TO RETURN A SUMMARY OF THIS SONG IN ONE SENTENCE (NO MORE THAN 15 WORDS)")
COUNTRY_CALCULATION_PROMPT = ("YOU WILL RECEIVE A TEXT WITH SONG LYRICS."
                              " YOUR TASK IS TO CREATE A VALID PYTHON LIST WITH THE"
                              " NAMES OF COUNTRIES THAT CAN BE IN THAT LYRICS. "
                              "RETURN AN EMPTY LIST IF THERE ARE NO COUNTRIES. "
                              "DO NOT ADD ANY OTHER TEXT OR SYMBOLS APART FROM THAT LIST")